In [38]:
#Gautami Kadam
import pandas as pd
import numpy as np
import tensorflow as tf
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score

In [39]:
#Gautami Kadam
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense,Dropout

In [3]:
#Gautami Kadam
df = pd.read_csv('train.csv')

In [4]:
#Gautami Kadam
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [5]:
#Gautami Kadam
df = df.dropna()

In [6]:
#Gautami Kadam
X = df.drop('label',axis=1)

In [7]:
#Gautami Kadam
y = df['label']

In [8]:
#Gautami Kadam
X.shape

(18285, 4)

In [9]:
#Gautami Kadam
y.shape

(18285,)

In [10]:
#Gautami Kadam
tf.__version__

'2.8.0'

In [11]:
#Gautami Kadam
#Vocabulary size
voc_size = 5000

In [12]:
#One hot representation

In [13]:
#Gautami Kadam
mes = X.copy()

In [14]:
#Gautami Kadam
mes['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [15]:
#as we droped nan values so need to reset indexes
mes.reset_index(inplace=True)

In [16]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [17]:
#Gautami Kadam
ps = PorterStemmer()
string = "At: What time?"
match = re.sub("[^a-zA-Z]"," ",string)
print(match)
match = match.lower()
print(match)
match = match.split()
print(match)
review = [ps.stem(word) for word in match if not word in stopwords.words('english')]
print(review)
review = ' '.join(review)
print(review)

At  What time 
at  what time 
['at', 'what', 'time']
['time']
time


In [18]:
#use of stem
#the idea of stemming is a sort of normalizing method. Many variataions 
#of words carry the same meaning, other than when tense is involved
#the reason why we stem is to shorten the lookup, and normalize sentences
ex_words = ["python","pythoner","pythoning","pythoned","pythonly"]
for w in ex_words:
    print(ps.stem(w))

python
python
python
python
pythonli


In [23]:
corpus = []
for i in range(0,len(mes)):
    rev = re.sub('[^a-zA-Z]',' ',mes['title'][i])
    rev = rev.lower()
    rev = rev.split()
    
    rev = [ps.stem(word) for word in rev if not word in stopwords.words('english')]
    rev = ' '.join(rev)
    corpus.append(rev)

In [24]:
#Gautami Kadam
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [25]:
onehot_rep = [one_hot(words,voc_size)for words in corpus]
onehot_rep

[[1693, 4759, 4174, 3474, 2458, 2643, 1008, 1892, 134, 1677],
 [1261, 2266, 1192, 1900, 4647, 3358, 4466],
 [1724, 4676, 4814, 2203],
 [4596, 4802, 377, 3523, 3339, 1638],
 [1743, 4647, 3480, 1581, 4278, 1031, 4647, 2514, 2478, 1032],
 [3014,
  1149,
  4955,
  2194,
  980,
  2854,
  1354,
  3889,
  2089,
  1131,
  4299,
  426,
  4514,
  4218,
  4466],
 [1686, 4165, 2764, 631, 2796, 4025, 472, 1120, 2480, 3035, 1538],
 [925, 1693, 2565, 1016, 954, 262, 2854, 3824, 2480, 3035, 1538],
 [675, 1992, 1056, 4158, 2986, 3312, 1386, 806, 2854, 2897],
 [1577, 3351, 3968, 4946, 2369, 1033, 500, 2769],
 [2190, 4492, 3343, 32, 3607, 4415, 1653, 358, 2436, 1854, 3123],
 [3523, 250, 2458, 3312, 2854, 954],
 [940, 2542, 3435, 1588, 2091, 758, 1253, 3715, 4293],
 [4714, 2767, 4706, 3603, 3975, 547, 1865, 2480, 3035, 1538],
 [1299, 1928, 3376, 4537, 3468, 2480, 3035, 1538],
 [2304, 627, 3227, 1574, 3175, 2527, 3412, 1774, 390, 2384],
 [2245, 1342, 2266],
 [4894, 264, 1385, 4880, 2854, 2963, 2863, 4466],

In [28]:
length = 20
embed_docs = pad_sequences(onehot_rep,padding='pre',maxlen=length)
print(embed_docs)

[[   0    0    0 ... 1892  134 1677]
 [   0    0    0 ... 4647 3358 4466]
 [   0    0    0 ... 4676 4814 2203]
 ...
 [   0    0    0 ... 2480 3035 1538]
 [   0    0    0 ...  839 1521  908]
 [   0    0    0 ... 1243 4786 2169]]


In [29]:
#Gautami Kadam
embed_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1693,
       4759, 4174, 3474, 2458, 2643, 1008, 1892,  134, 1677])

In [31]:
embed_vector_feature = 40
model = Sequential()
model.add(Embedding(voc_size,embed_vector_feature,input_length=length))
#one LSTM uses 100 neurons
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [33]:
#Gautami Kadam
len(embed_docs),y.shape

(18285, (18285,))

In [36]:
X_final = np.array(embed_docs)
y_final = np.array(y)

In [37]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [40]:
X_train,X_test,y_train,y_test = train_test_split(X_final,y_final,test_size=0.33,random_state=42)

In [47]:
#model training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 14s 50ms/step - loss: 0.3393 - accuracy: 0.8340 - val_loss: 0.2001 - val_accuracy: 0.9152
Epoch 2/10
192/192 [==============================] - 8s 44ms/step - loss: 0.1544 - accuracy: 0.9393 - val_loss: 0.1937 - val_accuracy: 0.9210
Epoch 3/10
192/192 [==============================] - 8s 44ms/step - loss: 0.1147 - accuracy: 0.9568 - val_loss: 0.2080 - val_accuracy: 0.9226
Epoch 4/10
192/192 [==============================] - 9s 45ms/step - loss: 0.0868 - accuracy: 0.9686 - val_loss: 0.2388 - val_accuracy: 0.9180
Epoch 5/10
192/192 [==============================] - 9s 44ms/step - loss: 0.0628 - accuracy: 0.9779 - val_loss: 0.2592 - val_accuracy: 0.9114
Epoch 6/10
192/192 [==============================] - 9s 45ms/step - loss: 0.0527 - accuracy: 0.9824 - val_loss: 0.2873 - val_accuracy: 0.9123
Epoch 7/10
192/192 [==============================] - 9s 45ms/step - loss: 0.0383 - accuracy: 0.9862 - val_loss: 0.3017 - val_accuracy: 0.918

In [42]:
#Gautami Kadam
embed_vector_feature = 40
model = Sequential()
model.add(Embedding(voc_size,embed_vector_feature,input_length=length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [48]:
y_pred = (model.predict(X_test)>0.5).astype("int32")

In [49]:
#Gautami Kadam
confusion_matrix(y_test,y_pred)

array([[3138,  281],
       [ 274, 2342]], dtype=int64)

In [50]:
#Gautami Kadam
accuracy_score(y_test,y_pred)

0.908036454018227